### ISSUE TITLE
k8s-libsonnet: Text block's first line must start with whitespace

### ISSUE THREAD

**Issue by JaquelineP** [jsonnet-libs/k8s#308] opened 2023-04-24 12:45 UTC
Hi,

I'll try to run the k8s-libsonnet sample from the documentation: https://jsonnet-libs.github.io/k8s-libsonnet/
When executing `tk show environments/qa' to render the yaml which will be applied, the following error occurs:
```
$ tk show environments/qa/
Error: evaluating jsonnet: RUNTIME ERROR: C:\DEV\projects\eip-1427\vendor\github.com\jsonnet-libs\k8s-libsonnet\1.26\_custom\core.libsonnet:42:29 Text block's first line must start with whitespace
        C:\DEV\projects\eip-1427\vendor\github.com\jsonnet-libs\k8s-libsonnet\1.26\main.libsonnet:1:145-176     $
        C:\DEV\projects\eip-1427\environments\qa\main.jsonnet:2:14-80   object <anonymous>
        C:\DEV\projects\eip-1427\environments\qa\main.jsonnet:3:8-9
        Field "foo"
        During manifestation
```

Any help is appreciated!

**Comment by Duologic** [comment] 2023-04-28 07:21
Looks like the rendered docs are not 100% correct, but I don't see how you reach this part of the code, can you share a minimally reproducible example so we can test and eventually fix this issue?

**Comment by Duologic** [comment] 2024-10-11 12:15
Didn't get a response, closing.

**Closed by Duologic** 2024-10-11 12:15 UTC
Labels: possible-bug
